apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Official ArgoCD installation manifest
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

# Custom changes (patches) that will merge with the official files
patchesStrategicMerge:
  - argocd-cm-patch.yaml
  - argocd-rbac-cm-patch.yaml
