apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres
  namespace: url-shortener

spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:

    metadata:
      labels:
        app: postgres
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "url-shortener"
        vault.hashicorp.com/agent-inject-secret-username: "secret/data/database"
        vault.hashicorp.com/agent-inject-template-username: |
          {{- with secret "secret/data/database" -}}
          {{ .Data.data.POSTGRES_USER }}
          {{- end -}}
        vault.hashicorp.com/agent-inject-secret-password: "secret/data/database"
        vault.hashicorp.com/agent-inject-template-password: |
          {{- with secret "secret/data/database" -}}
          {{ .Data.data.POSTGRES_PASSWORD }}
          {{- end -}}

    spec:
      serviceAccountName: url-shortener-sa
      containers:
        - name: postgres

          image: postgres:17

          ports:
            - containerPort: 5432

          env:

            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_DB

            - name: POSTGRES_USER_FILE
              value: "/vault/secrets/username"

            - name: POSTGRES_PASSWORD_FILE
              value: "/vault/secrets/password"

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: postgres-storage

          persistentVolumeClaim:
            claimName: postgres-pvc
